# -*- coding: utf-8 -*-
"""cifar10_SVC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BY-DNLQp15H5yj1AsQdqmLMgg0cgiyBO
"""

import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn import svm
import pandas as pd
import numpy as np
import tensorflow as tf
import time
from sklearn import metrics
from sklearn.svm import LinearSVC

cifar10=tf.keras.datasets.cifar10

(x_train,y_train),(x_test,y_test)=cifar10.load_data()

y_test

from matplotlib import pyplot
for i in range(4):  
  pyplot.subplot(330 + 5 + i)
  pyplot.imshow(x_train[i], cmap=pyplot.get_cmap('gray'))
  pyplot.show()

print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

x_train, x_test = x_train / 255.0, x_test / 255.0

x_train=x_train.flatten().reshape(50000,3072)
x_test=x_test.flatten().reshape(10000,3072)
#y_train, y_test = y_train.flatten(), y_test.flatten()

from sklearn.decomposition import PCA

pca = PCA().fit(x_train)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.grid()
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

pca=PCA(n_components=100)
pca.fit(x_train)
x_train=pca.transform(x_train)
x_test=pca.transform(x_test)

print(x_train.shape)
print(x_test.shape)

#with svm.SVC
import time
start=time.time()
model=svm.SVC(decision_function_shape="ovo",C=0.1)
model.fit(x_train,y_train)
end=time.time()

elapsed_time=end-start
print(elapsed_time)

y_predicted=model.predict(x_test.flatten().reshape(10000,100))
y_predicted_train=model.predict(x_train.flatten().reshape(50000,100))

print(metrics.accuracy_score(y_test,y_predicted))
print(metrics.accuracy_score(y_train,y_predicted_train))

f1=metrics.f1_score(y_test, y_predicted, average="macro")
acc=metrics.accuracy_score(y_test,y_predicted)
rec=metrics.recall_score(y_test,y_predicted, average="macro")
pr=metrics.precision_score(y_test, y_predicted, average="macro")
print(f1)
print(acc)
print(rec)
print(pr)

from sklearn.metrics import confusion_matrix
from sklearn.metrics._plot.confusion_matrix import ConfusionMatrixDisplay
cm=confusion_matrix(y_test,y_predicted)
disp=ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Confusion matrix")
plt.show()

Fls=[]
for i in range(len(y_test)):
  if y_test[i]!=y_predicted[i]:
    Fls.append(i)
print(len(Fls))







(x_train,y_train),(x_test,y_test)=cifar10.load_data()
import numpy as np
random_idx=np.random.choice(Fls)
x_sample=x_test[random_idx]
y_sample_true=y_test[random_idx]
y_sample_pred_class=y_predicted[random_idx]

plt.title("Predicted: {},True: {}".format(y_sample_pred_class,y_sample_true),fontsize=16)
plt.imshow(x_sample,cmap="gray")

#with LinearSVC
start=time.time()
linear_svc=LinearSVC(dual=False)
linear_svc.fit(x_pca_train,y_train)
end=time.time()

elapsed_time=end-start
print(elapsed_time)
y_pred=linear_svc.predict(x_pca_test.flatten().reshape(10000,120))
accuracy=metrics.accuracy_score(y_test,y_pred)
accuracy