# -*- coding: utf-8 -*-
"""mnist_SVC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Am0wG2d-veMqFJOgyMW9zXTGE6HT12p
"""

#from sklearn. datasets import load_digits 
from sklearn import metrics
import pandas as pd 
import matplotlib. pyplot as plt 
from keras.datasets import mnist
from sklearn import svm
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import metrics
import keras
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

(X_train, y_train), (X_test, y_test) = mnist.load_data()

from matplotlib import pyplot
for i in range(4):  
  pyplot.subplot(330 + 1 + i)
  pyplot.imshow(X_train[i], cmap=pyplot.get_cmap('gray'))
  pyplot.show()

X_train=X_train.flatten().reshape(60000,784)
X_test=X_test.flatten().reshape(10000,784)
X_train=X_train/255.0
X_test=X_test/255.0

from sklearn.decomposition import PCA
import numpy as np

pca=PCA().fit(X_train)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.grid()
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')

pca=PCA(n_components=100)
pca.fit(X_train)

X_train=pca.transform(X_train)
X_test=pca.transform(X_test)

X_train.shape

import time
start=time.time()
model=svm.SVC(kernel="sigmoid",C=10,gamma=0.1)
model.fit(X_train,y_train)
end=time.time()

elapsed_time=end-start 
print(elapsed_time)

y_predicted=model.predict(X_test)
y_predicted_train=model.predict(X_train)

acc_test=metrics.accuracy_score(y_test,y_predicted)
acc_train=metrics.accuracy_score(y_train,y_predicted_train)
print(acc_test)
print(acc_train)

f1=metrics.f1_score(y_test, y_predicted, average="macro")
acc=metrics.accuracy_score(y_test,y_predicted)
rec=metrics.recall_score(y_test,y_predicted, average="macro")
pr=metrics.precision_score(y_test, y_predicted, average="macro")
print(f1)
print(acc)
print(rec)
print(pr)

from sklearn.metrics import confusion_matrix
from sklearn.metrics._plot.confusion_matrix import ConfusionMatrixDisplay
cm=confusion_matrix(y_test,y_predicted)
disp=ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Confusion matrix")
plt.show()

Fls=[]
for i in range(len(y_test)):
  if y_test[i]!=y_predicted[i]:
    Fls.append(i)
print(len(Fls))

import numpy as np
random_idx=np.random.choice(Fls)
x_sample=X_test[random_idx]
y_sample_true=y_test[random_idx]
y_sample_pred_class=y_predicted[random_idx]

plt.title("Predicted: {},True: {}".format(y_sample_pred_class,y_sample_true),fontsize=16)
plt.imshow(x_sample,cmap="gray")

CR=classification_report(y_test,y_predicted)
print("Classification report \n")
print(CR)